backend:
  name: github
  repo: giglifegamingaz/giglife-gaming-site
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "body", widget: "text" }
      - { label: "Product Image", name: "image", widget: "image" }
